"""03_registered: registered (and documented-deviation) hypothesis tests

Generated by filedrawer 0.1.0. Run from the study folder: python scripts/03_registered.py
"""
import json
import pathlib
import sys
import warnings

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")
ROOT = pathlib.Path(__file__).resolve().parents[1]

import statsmodels.formula.api as smf
from scipy import stats as sps
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

HYPOTHESES = json.loads("[{\"id\": \"H1\", \"text\": \"Each intervention changes total discernment accuracy relative to control.\", \"outcome\": \"total_score\", \"treatment\": {\"column\": \"treatment\", \"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\"}, \"direction\": \"two_sided\", \"estimator\": {\"kind\": \"lin\", \"robust\": \"HC2\", \"cluster\": null, \"weights\": \"ipw\", \"covariates\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"], \"continuous\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"]}, \"pooled\": true, \"subgroup\": null, \"exclusions\": []}, {\"id\": \"H2\", \"text\": \"Each intervention changes accuracy on AI-generated items relative to control.\", \"outcome\": \"fake_score\", \"treatment\": {\"column\": \"treatment\", \"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\"}, \"direction\": \"two_sided\", \"estimator\": {\"kind\": \"lin\", \"robust\": \"HC2\", \"cluster\": null, \"weights\": \"ipw\", \"covariates\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"], \"continuous\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"]}, \"pooled\": true, \"subgroup\": null, \"exclusions\": []}, {\"id\": \"H3\", \"text\": \"Each intervention changes accuracy on real items relative to control.\", \"outcome\": \"real_score\", \"treatment\": {\"column\": \"treatment\", \"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\"}, \"direction\": \"two_sided\", \"estimator\": {\"kind\": \"lin\", \"robust\": \"HC2\", \"cluster\": null, \"weights\": \"ipw\", \"covariates\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"], \"continuous\": [\"media_trust\", \"political_interest\", \"pk_score\", \"ai_scale\"]}, \"pooled\": true, \"subgroup\": null, \"exclusions\": []}]")
SUBGROUPS = json.loads("[]")
MULTIARM = json.loads("{\"H1\": {\"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\", \"labels\": {\"1\": \"Flagging\", \"2\": \"Provenance\", \"3\": \"Automated Flagging\", \"4\": \"AI Accuracy Nudge\", \"5\": \"Breathing Exercise\", \"6\": \"Mindfulness\", \"7\": \"Inoculation\", \"8\": \"AI Literacy Infographic\", \"9\": \"AI Literacy Infographic 2\", \"10\": \"AI Literacy Guide\", \"11\": \"AI Text Video\", \"0\": \"Control\"}, \"pooled\": true}, \"H2\": {\"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\", \"labels\": {\"1\": \"Flagging\", \"2\": \"Provenance\", \"3\": \"Automated Flagging\", \"4\": \"AI Accuracy Nudge\", \"5\": \"Breathing Exercise\", \"6\": \"Mindfulness\", \"7\": \"Inoculation\", \"8\": \"AI Literacy Infographic\", \"9\": \"AI Literacy Infographic 2\", \"10\": \"AI Literacy Guide\", \"11\": \"AI Text Video\", \"0\": \"Control\"}, \"pooled\": true}, \"H3\": {\"arms\": [\"1\", \"2\", \"3\", \"4\", \"5\", \"6\", \"7\", \"8\", \"9\", \"10\", \"11\"], \"control\": \"0\", \"labels\": {\"1\": \"Flagging\", \"2\": \"Provenance\", \"3\": \"Automated Flagging\", \"4\": \"AI Accuracy Nudge\", \"5\": \"Breathing Exercise\", \"6\": \"Mindfulness\", \"7\": \"Inoculation\", \"8\": \"AI Literacy Infographic\", \"9\": \"AI Literacy Infographic 2\", \"10\": \"AI Literacy Guide\", \"11\": \"AI Text Video\", \"0\": \"Control\"}, \"pooled\": true}}")     # hypothesis id -> {arms, control, labels, pooled}
CATEGORICAL = set(["ai_outcome_1", "ai_outcome_2", "ai_outcome_3", "ai_outcome_4", "ai_outcome_5", "ai_outcome_6", "ai_outcome_7", "pk_1", "pk_2", "political_interest", "trust_online_1", "trust_online_2", "trust_online_3", "trust_online_4", "trust_online_5", "trust_online_6", "trust_online_7"])
ALPHA = 0.05
RES = ROOT / "results"; FIG = ROOT / "figures"
RES.mkdir(exist_ok=True); FIG.mkdir(exist_ok=True)

def arm_str(v):
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return None
    sv = str(v).strip()
    try:
        f = float(sv)
    except ValueError:
        return sv
    return str(int(f)) if f.is_integer() else sv

def cat_set(est):
    """Categorical covariates for one hypothesis: codebook-labelled columns, plus estimator.categorical,
    minus estimator.continuous (lets a plan pin an ordinal item as continuous, as the original model did)."""
    return (CATEGORICAL | set(est.get("categorical") or [])) - set(est.get("continuous") or [])

def term(c, cats=CATEGORICAL):
    return f"C({c})" if c in cats else c

def fit(df, formula, est):
    kw = {}
    cl = est.get("cluster")
    if cl:
        kw = dict(cov_type="cluster", cov_kwds={"groups": df[cl]})
    else:
        kw = dict(cov_type=est.get("robust") or "HC2")
    w = est.get("weights")
    model = smf.wls(formula, data=df, weights=df[w]) if w else smf.ols(formula, data=df)
    return model.fit(**kw)

def centered(d, covs, cats=CATEGORICAL):
    """Lin (2013): covariates centred at their sample means; categorical covariates become centred dummies.
    Returns (data, list of centred column names)."""
    cols = []
    for c in covs:
        if c in cats:
            dums = pd.get_dummies(d[c].astype(str), prefix=c, drop_first=True, dtype=float)
            for k in dums.columns:
                name = "".join(ch if ch.isalnum() else "_" for ch in k) + "_c"
                d[name] = dums[k] - dums[k].mean()
                cols.append(name)
        else:
            d[c + "_c"] = pd.to_numeric(d[c], errors="coerce") - pd.to_numeric(d[c], errors="coerce").mean()
            cols.append(c + "_c")
    return d, cols

def build_formula(y, est, covs, d, arm_term="treat"):
    kind = est.get("kind", "ols")
    if kind == "diff_means" or not covs:
        return f"{y} ~ {arm_term}", d
    cats = cat_set(est)
    if kind == "lin":
        d, cc = centered(d, covs, cats)
        return f"{y} ~ {arm_term} * ({' + '.join(cc)})", d
    return f"{y} ~ {arm_term}" + "".join(f" + {term(c, cats)}" for c in covs), d

def tidy(res, analysis_id):
    ci = res.conf_int()
    rows = []
    for t in res.params.index:
        rows.append({"analysis_id": analysis_id, "term": t, "estimate": res.params[t], "std_error": res.bse[t],
                     "statistic": res.tvalues[t], "p_value": res.pvalues[t], "conf_low": ci.loc[t, 0], "conf_high": ci.loc[t, 1]})
    return pd.DataFrame(rows)

def directional_p(est, p, direction):
    """p-value matching the hypothesis: one-sided for a stated direction (half the two-sided p when the
    estimate has the predicted sign, 1 - p/2 otherwise), two-sided otherwise."""
    if direction == "positive":
        return float(p / 2 if est > 0 else 1 - p / 2)
    if direction == "negative":
        return float(p / 2 if est < 0 else 1 - p / 2)
    return float(p)

def supported(est, p, direction):
    return bool(directional_p(est, p, direction) < ALPHA)

def pool(effects, variances):
    """Random-effects pooled estimate (iterated tau^2; DerSimonian-Laird fallback).
    The arm effects share one control group, so they are not independent: the pooled SE is approximate."""
    from statsmodels.stats.meta_analysis import combine_effects
    eff, var = np.asarray(effects, float), np.asarray(variances, float)
    try:
        cr = combine_effects(eff, var, method_re="iterated")
        if not np.isfinite(cr.tau2):
            raise ValueError("tau2 not finite")
        method = "iterated"
    except Exception:
        cr = combine_effects(eff, var, method_re="dl")
        method = "dl"
    est, se = float(cr.mean_effect_re), float(cr.sd_eff_w_re)
    p = float(2 * sps.norm.sf(abs(est / se))) if se > 0 else float("nan")
    i2 = float(max(0.0, min(1.0, cr.i2))) if np.isfinite(cr.i2) else float("nan")
    return {"estimate": est, "std_error": se, "p_value": p, "tau2": float(cr.tau2), "i2": i2, "method": method,
            "conf_low": est - 1.96 * se, "conf_high": est + 1.96 * se}

def forest(hid, arms_df, pooled, outcome):
    a = arms_df.sort_values("estimate").reset_index(drop=True)
    k = len(a)
    fig, ax = plt.subplots(figsize=(6.5, 1.6 + 0.4 * (k + 1)))
    ys = np.arange(k) + 1
    ax.errorbar(a["estimate"], ys, xerr=[a["estimate"] - a["conf_low"], a["conf_high"] - a["estimate"]],
                fmt="o", color="#2457a6", ecolor="#2457a6", capsize=3, ms=4)
    labels = [f"{l} (n={int(n)})" for l, n in zip(a["arm_label"], a["n_arm"])]
    if pooled is not None:
        ax.plot([pooled["conf_low"], pooled["estimate"], pooled["conf_high"], pooled["estimate"], pooled["conf_low"]],
                [0, 0.2, 0, -0.2, 0], color="#d9822b", lw=1.2)
        ax.fill([pooled["conf_low"], pooled["estimate"], pooled["conf_high"], pooled["estimate"]], [0, 0.2, 0, -0.2], color="#d9822b", alpha=0.6)
        ax.axvline(pooled["estimate"], color="#d9822b", lw=1, ls="--")
        ys = np.concatenate([[0], ys]); labels = ["Pooled (random effects)"] + labels
    ax.axvline(0, color="#888", lw=1)
    ax.set_yticks(ys); ax.set_yticklabels(labels, fontsize=8)
    ax.set_xlabel(f"Effect on {outcome} vs control (95% CI)")
    ax.set_title(f"{hid}: treatment arms", fontsize=10)
    ax.spines[["top", "right"]].set_visible(False)
    fig.tight_layout(); fig.savefig(FIG / f"{hid}_arms.png", dpi=150); plt.close(fig)

def run_multiarm(h, d, est, covs):
    spec = MULTIARM[h["id"]]
    arms, control = spec["arms"], spec["control"]
    y = h["outcome"]
    d = d.copy()
    d["arm_code"] = d["arm_code"].map(arm_str)
    d = d[d["arm_code"].isin(arms + [control])]
    extra = [c for c in (est.get("weights"), est.get("cluster")) if c]
    eligible = d["arm_code"].value_counts()
    n_eligible = int(len(d))
    d = d.dropna(subset=[y, "arm_code"] + covs + extra)
    if n_eligible - len(d):
        print(f"{h['id']}: dropped {n_eligible - len(d)} of {n_eligible} eligible rows with a missing outcome, covariate, weight or cluster value")
    arm_term = f"C(arm_code, Treatment(reference={control!r}))"
    formula, d = build_formula(y, est, covs, d, arm_term)
    res = fit(d, formula, est)
    tidy(res, h["id"]).to_csv(RES / f"{h['id']}.csv", index=False)
    ci = res.conf_int()
    mean_control = d.loc[d["arm_code"] == control, y].mean()
    direction = h.get("direction", "two_sided")
    rows, summary = [], []
    for a in arms:
        t = f"{arm_term}[T.{a}]"
        if t not in res.params.index:
            print(f"WARNING: {h['id']} arm {a} has no coefficient (no observations?)")
            continue
        e, se, p = float(res.params[t]), float(res.bse[t]), float(res.pvalues[t])
        n_arm = int((d["arm_code"] == a).sum())
        rows.append({"analysis_id": f"{h['id']}:{a}", "arm_code": a, "arm_label": spec["labels"].get(a, a), "estimate": e,
                     "std_error": se, "p_value": p, "conf_low": float(ci.loc[t, 0]), "conf_high": float(ci.loc[t, 1]),
                     "n_arm": n_arm, "n_arm_eligible": int(eligible.get(a, 0)), "mean_control": mean_control,
                     "mean_arm": d.loc[d["arm_code"] == a, y].mean(), "p_directional": directional_p(e, p, direction),
                     "supported": supported(e, p, direction)})
        summary.append({"analysis_id": f"{h['id']}:{a}", "outcome": y, "formula": formula, "cov_type": res.cov_type,
                        "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
                        "mean_control": mean_control, "mean_treated": rows[-1]["mean_arm"], "direction": direction,
                        "p_directional": directional_p(e, p, direction), "n_eligible": n_eligible,
                        "n_control": int((d["arm_code"] == control).sum()),
                        "supported": rows[-1]["supported"], "term": t, "arm": a, "weights": est.get("weights") or ""})
    arms_df = pd.DataFrame(rows)
    arms_df.to_csv(RES / f"{h['id']}_arms.csv", index=False)
    pooled = None
    if spec.get("pooled", True) and len(arms_df) >= 2:
        pooled = pool(arms_df["estimate"], arms_df["std_error"] ** 2)
        summary.append({"analysis_id": f"{h['id']}:pooled", "outcome": y, "formula": formula, "cov_type": res.cov_type,
                        "estimate": pooled["estimate"], "std_error": pooled["std_error"], "p_value": pooled["p_value"], "n": int(res.nobs),
                        "mean_control": mean_control, "mean_treated": d.loc[d["arm_code"] != control, y].mean(), "direction": direction,
                        "p_directional": directional_p(pooled["estimate"], pooled["p_value"], direction), "n_eligible": n_eligible,
                        "n_control": int((d["arm_code"] == control).sum()),
                        "supported": supported(pooled["estimate"], pooled["p_value"], direction), "arm": "pooled",
                        "weights": est.get("weights") or "", "tau2": pooled["tau2"], "i2": pooled["i2"], "pooled_method": pooled["method"],
                        "k_arms": int(len(arms_df))})
    forest(h["id"], arms_df, pooled, y)
    n_sig = int(arms_df["supported"].sum()) if len(arms_df) else 0
    print(f"{h['id']}: {formula} | {len(arms_df)} arms vs {spec['labels'].get(control, control)}, N={int(res.nobs)}, "
          f"{res.cov_type} SEs{', weights=' + est['weights'] if est.get('weights') else ''}; {n_sig} arm(s) supported"
          + (f"; pooled={pooled['estimate']:.3f} (SE {pooled['std_error']:.3f}, p={pooled['p_value']:.4f}, tau2={pooled['tau2']:.4f}, I2={pooled['i2']:.2f})" if pooled else ""))
    return summary

def main():
    df = pd.read_csv(ROOT / "data" / "clean.csv")
    summary = []
    for h in HYPOTHESES:
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception as e:
                print(f"WARNING: {h['id']} exclusion {expr!r} skipped: {e}")
        est = h.get("estimator", {})
        covs = est.get("covariates") or []
        if h["id"] in MULTIARM:
            summary += run_multiarm(h, d, est, covs)
            continue
        contrast = [arm_str(x) for x in ((h.get("treatment") or {}).get("contrast") or [])]
        if len(contrast) == 2 and "arm_code" in d.columns:
            # restrict to the two contrasted arms (a no-op in a two-arm design)
            codes = d["arm_code"].map(arm_str)
            d = d[codes.isin(contrast)].copy()
            d["treat"] = (d["arm_code"].map(arm_str) == contrast[0]).astype(int)
        extra = [c for c in (est.get("weights"), est.get("cluster")) if c]
        n_eligible = int(len(d))
        d = d.dropna(subset=[h["outcome"], "treat"] + covs + extra)
        if n_eligible - len(d):
            print(f"{h['id']}: dropped {n_eligible - len(d)} of {n_eligible} eligible rows with a missing outcome, covariate, weight or cluster value")
        formula, d = build_formula(h["outcome"], est, covs, d)
        res = fit(d, formula, est)
        tidy(res, h["id"]).to_csv(RES / f"{h['id']}.csv", index=False)
        e, se, p = res.params["treat"], res.bse["treat"], res.pvalues["treat"]
        g = d.groupby("treat")[h["outcome"]].agg(["mean", "std", "count"])
        row = {"analysis_id": h["id"], "outcome": h["outcome"], "formula": formula, "cov_type": res.cov_type,
               "estimate": e, "std_error": se, "p_value": p, "n": int(res.nobs),
               "mean_control": g.loc[0, "mean"] if 0 in g.index else np.nan,
               "mean_treated": g.loc[1, "mean"] if 1 in g.index else np.nan,
               "direction": h.get("direction", "two_sided"), "p_directional": directional_p(e, p, h.get("direction", "two_sided")),
               "n_eligible": n_eligible, "supported": supported(e, p, h.get("direction", "two_sided"))}
        if est.get("weights"):
            row["weights"] = est["weights"]
        summary.append(row)
        print(f"{h['id']}: {formula} | ATE={e:.3f} (SE {se:.3f}, p={p:.4f}, N={int(res.nobs)})")
    hyps = {h["id"]: h for h in HYPOTHESES}
    for s in SUBGROUPS:
        h = hyps.get(s["hypothesis"])
        if h is None:
            continue
        d = df.copy()
        for expr in h.get("exclusions") or []:
            try:
                d = d.query(expr)
            except Exception:
                pass
        levels = s.get("levels") or {}
        mod = s["moderator"]
        if levels:
            d = d[d[mod].astype(str).isin([str(k) for k in levels])]
        d = d.dropna(subset=[h["outcome"], "treat", mod])
        d["_mod"] = d[mod].astype(str).map({str(k): v for k, v in levels.items()}) if levels else d[mod].astype(str)
        res = fit(d, f"{h['outcome']} ~ treat * C(_mod)", h.get("estimator", {}))
        tidy(res, s["id"]).to_csv(RES / f"{s['id']}.csv", index=False)
        inter = [t for t in res.params.index if t.startswith("treat:")]
        rows = []
        for lvl, sub in d.groupby("_mod"):
            r = fit(sub, f"{h['outcome']} ~ treat", h.get("estimator", {}))
            rows.append({"analysis_id": s["id"], "level": lvl, "estimate": r.params["treat"], "std_error": r.bse["treat"],
                         "p_value": r.pvalues["treat"], "n": int(r.nobs)})
        pd.DataFrame(rows).to_csv(RES / f"{s['id']}_by_level.csv", index=False)
        for t in inter:
            summary.append({"analysis_id": s["id"], "outcome": h["outcome"], "formula": f"{h['outcome']} ~ treat * C({mod})",
                            "cov_type": res.cov_type, "estimate": res.params[t], "std_error": res.bse[t], "p_value": res.pvalues[t],
                            "n": int(res.nobs), "mean_control": np.nan, "mean_treated": np.nan, "direction": "two_sided",
                            "supported": bool(res.pvalues[t] < ALPHA), "term": t})
            print(f"{s['id']}: interaction {t} = {res.params[t]:.3f} (SE {res.bse[t]:.3f}, p={res.pvalues[t]:.4f})")
    pd.DataFrame(summary).to_csv(RES / "registered_summary.csv", index=False)
    # coefficient plot: one row per two-arm hypothesis and per pooled multi-arm estimate
    main_rows = [r for r in summary if "term" not in r]
    if main_rows:
        fig, ax = plt.subplots(figsize=(6, 0.8 + 0.6 * len(main_rows)))
        ys = range(len(main_rows))
        ax.errorbar([r["estimate"] for r in main_rows], list(ys), xerr=[1.96 * r["std_error"] for r in main_rows],
                    fmt="o", color="#2457a6", ecolor="#2457a6", capsize=3)
        ax.axvline(0, color="#888", lw=1)
        ax.set_yticks(list(ys)); ax.set_yticklabels([f"{r['analysis_id']}: {r['outcome']}" for r in main_rows])
        ax.set_xlabel("Treatment effect (95% CI)")
        ax.spines[["top", "right"]].set_visible(False)
        fig.tight_layout(); fig.savefig(FIG / "registered_effects.png", dpi=150); plt.close(fig)
    print(f"wrote results/registered_summary.csv ({len(summary)} rows)")

if __name__ == "__main__":
    main()
